---
title: "Paper de Referencia"
subtitle: "A high-resolution gridded dataset to assess electrification in sub-Saharan Africa"
---

 _"A high-resolution gridded dataset to assess electrification in sub-Saharan africa"_ @Falchetta_2019
 
versión Online: [https://www.nature.com/articles/s41597-019-0122-6.pdf](https://www.nature.com/articles/s41597-019-0122-6.pdf)

## Abstract

Los datos espacialmente explícitos sobre el acceso y el uso de la electricidad son esenciales para la elaboración de políticas eficaces y la planificación de infraestructuras en regiones de renta baja y escasez de datos. Presentamos y validamos un conjunto de datos de 1 km de resolución sobre el acceso a la electricidad en el África subsahariana basado en datos reticulares sobre luz nocturna, población y ocupación del suelo. 

Utilizando distribuciones de probabilidad de irradiación luminosa, definimos niveles de consumo de electricidad para zonas urbanas y rurales y estimamos el reparto por niveles de los consumidores que viven en zonas electrificadas. Este planteamiento aporta nuevos conocimientos sobre la distribución espacial y la evolución temporal del acceso a la electricidad, así como una medida de su calidad que va más allá del acceso binario. 

Nuestras estimaciones son coherentes con las estadísticas nacionales y provinciales publicadas recientemente. Además, demostramos la coherencia entre los indicadores de calidad del acceso a la electricidad estimados y los niveles de consumo basados en encuestas y definidos de acuerdo con el Marco Multinivel del Banco Mundial. El conjunto de datos se reproduce y actualiza fácilmente utilizando un marco informático científico de acceso abierto. Los datos y el enfoque pueden aplicarse para mejorar la evaluación de las opciones de electrificación menos costosas y examinar los vínculos entre el acceso a la electricidad y otros objetivos de desarrollo sostenible.


## Background & Summary


El Objetivo de Desarrollo Sostenible 7 (ODS 7) de las Naciones Unidas (Sustainable Development Goal 7 -SDG 7) pretende garantizar el acceso a una energía asequible, fiable, sostenible y moderna para todos en 2030 @DESA. El acceso a los servicios de electricidad (metas 7.1.1 y 7.A y 7.B de los ODS) es una prioridad clave en el marco de este objetivo, también debido a las fuertes interconexiones que presenta con otros objetivos de desarrollo (@McCollum_2018, @Riva_2018, @Fuso_Nerini_2017, @Gertler_2017), pero su consecución a escala mundial presenta retos significativos. Se necesita información espacialmente explícita, actualizada y armonizada sobre el progreso de la electrificación para identificar dónde pueden centrarse los esfuerzos locales, nacionales e internacionales para lograr los mayores beneficios.


Iniciativas de seguimiento como el portal Progreso hacia una energía sostenible7, el Informe sobre el estado del acceso a la electricidad8 y la publicación de datos recopilados sobre el terreno9,10 han cuantificado el progreso de la electrificación en los últimos 20 años. Se calcula que en 2016 la población mundial sin acceso a la electricidad se redujo por debajo de los 1.000 millones11, en gran medida como resultado de los flujos de inversión internacionales12, el descenso de los costes de las soluciones de acceso distribuido (por ejemplo, la energía solar fotovoltaica)13 y los marcos políticos de apoyo14. De los que siguen sin acceso, unos 600 millones viven en el África subsahariana, donde 15 países tienen niveles de electrificación inferiores al 25%11.


La supervisión a escala nacional es importante para hacer un seguimiento regular de los esfuerzos. Sin embargo, evaluar la heterogeneidad subnacional es esencial para renderizar una imagen más clara del estado de electrificación de un país y mejorar la eficacia, el diseño y la implementación de planes de electrificación a escala local15,16. Esto se debe a que los esfuerzos de electrificación podrían concentrarse en regiones específicas, como las más cercanas a las conexiones de red existentes, mientras que el progreso podría seguir siendo lento o incluso estancarse en zonas más remotas que carecen de acceso a los recursos energéticos17,18. Además, se necesitan datos sobre las diferencias en los niveles de consumo para evaluar la calidad y la desigualdad del acceso y las consiguientes implicaciones de estas desigualdades de acceso19. Sin embargo, rara vez se dispone de datos reales sobre el consumo de electricidad con un alto nivel de res- olución espacial. La realización de encuestas sobre el terreno para recopilar estos datos es costosa y requiere mucho tiempo. En este contexto, existe un debate en curso sobre la mejor manera de proporcionar datos de buena calidad para hacer un seguimiento de los objetivos de acceso a la energía y reducir sus costes de recopilación y procesamiento, así como para tomar decisiones acertadas en un contexto de escasez de datos20.




![El diagrama de flujo representa las diferentes etapas, entradas de datos y salidas en la generación y validación de los datos. Azul: variables de teledetección; rojo: etapas de procesamiento; morado: métricas de salida; verde: datos de salida; blanco: conjuntos de datos de validación y apoyo; gris: etapas. @Falchetta_2019](images/workflow.png){#fig-WFgral fig-aling="center"}


Presentamos y validamos un conjunto de datos actualizables y totalmente reproducibles de 1 km de resolución sobre el acceso a la electricidad y los niveles de consumo en el África Subsahariana, basado en datos actualizados periódicamente sobre la luz nocturna, la población y la ocupación del suelo. El conjunto de datos se presenta en forma de archivos netCDF con recuentos del número de personas sin acceso en cada celda de 1 km2 para cada año entre 2014 y 2018 y el nivel estimado de consumo en cada píxel para 2018. Las estimaciones para cada métrica y país se validan con las cifras disponibles más recientes. Los datos pueden consultarse de forma interactiva en una interfaz web. Todo el código, desde la generación de datos hasta su procesamiento y exportación, está disponible para la reproducción de resultados. Cada mes se publican nuevas composiciones de NTL, lo que permite una actualización continua. Nuestras estimaciones coinciden en líneas generales tanto con los niveles de electrificación a nivel provincial basados en encuestas sobre el terreno notificados por las encuestas de demografía y salud, como con las cifras agregadas a nivel nacional publicadas anualmente por el informe Tracking SDG 7 de ESMAP/Banco Mundial. El conjunto de datos puede combinarse con otros datos a nivel regional e implementarse en una serie de estudios para desarrollar escenarios y modelar vías de acceso y demanda de energía en Modelos de Evaluación Integrada21,22 , evaluar opciones de electrificación de menor coste15 , realizar un seguimiento de los objetivos de desarrollo a escala local, diseñar infraestructuras y analizar los vínculos entre el acceso a la electricidad y otras métricas socioeconómicas y de bienestar.


La @fig-WFgral ilustra un esquema del marco informático científico de código abierto, que se analiza en detalle en la sección Métodos. Los recientes esfuerzos de recopilación de datos de alta resolución para la luz nocturna (NTL)23, la población24,25 y la cobertura del suelo26 , y las instalaciones de computación en nube para el procesamiento de datos espaciales27 permiten estimar la evolución del acceso a la electricidad y los niveles de consumo a nivel de píxel de 1 km2 . Empleamos el producto VIIRS-DNB (Visible Infrared Imaging Radiometer Suite, Day-Night Band) con corrección de luz difusa para la radiancia NTL (450 m de resolución en el ecuador) y los conjuntos de datos de distribución de población cuadriculados de LandScan (utilizado como fuente principal) y WorldPop (para comparación), ambos con una resolución de 1 km. WorldPop sólo se utilizó como fuente secundaria debido a posibles problemas de circularidad, ya que el modelo subyacente también utiliza NTL como entrada para estimar la población. Consulte [https://www.popgrid.org/compare-data](https://www.popgrid.org/compare-data) para obtener una visión comparativa de las entradas y la metodología de los diferentes conjuntos de datos de población. El uso de Landscan y WorldPop permite tener en cuenta el crecimiento reciente de la población (una media del 4,1 % en las zonas urbanas frente al 2,7 % para el conjunto del ASS en 2017, según los datos del Banco Mundial, [https://data.worldbank.org/](https://data.worldbank.org/)) y la dinámica migratoria.



Las luces nocturnas ya se han utilizado como indicador indirecto del acceso a la electricidad28-31, el consumo residencial32-37, la detección de cortes38-40, las fluctuaciones de población y la migración41,42, el PIB regional43,44 y la desigualdad de ingresos45. Sin embargo, ésta es la primera vez que se ha elaborado y validado un conjunto de datos totalmente reproducible y actualizable con este alto nivel de resolución para las estadísticas de SSA.



## Methods

Fuentes de datos y herramientas de procesamiento. Las fuentes de datos, descritas en la Tabla 1, incluyen los compuestos mensuales NTL VIIRS-DNB corregidos por luz parásita para los años 2014-201823 (que miden la radiancia y filtran la nubosidad), la población cuadriculada reducida de LandScan 2014 y 201724, y WorldPop 2015 y 202025 para el análisis de sensibilidad. Las tasas nacionales de acceso a la electricidad se han extraído del portal de seguimiento del ODS 7 de ESMAP/Banco Mundial7 , mientras que las cifras a nivel provincial se han extraído de una serie de encuestas sobre el terreno a través del compilador STATcompiler del Programa USAID/DHS para la evaluación comparativa subnacional10. Los datos de las encuestas de hogares para validar los niveles de consumo se han obtenido de la Biblioteca de Microdatos del Banco Mundial ([http://microdata.worldbank.org](http://microdata.worldbank.org)). Para definir los países, adoptamos el conjunto de datos de límites administrativos globales (GADM) v3.646.

```{r}

```



La plataforma Google Earth Engine27 se utiliza para procesar imágenes de satélite y extraer datos, que posteriormente se emplean para producir los conjuntos de datos y graficar en el entorno de computación científica R. La sección Disponibilidad del código y registros de datos enlaza con los repositorios que alojan el código Javascript del motor Earth Engine y el script R, lo que permite reproducir los resultados, alterar los parámetros para realizar análisis de sensibilidad adicionales u otras mejoras implementadas por nuevos usuarios. Los resultados también se visualizan dinámicamente en una interfaz web, en https:// gdessa.ene.iiasa.ac.at.




**Identificación de zonas urbanas y rurales**. La definición de urbanización es muy variable entre países y regiones tanto de África47,48 como del mundo entero28. La definición de población urbana y rural de las Naciones Unidas está estrechamente vinculada a factores políticos y administrativos que dificultan la generalización de la estructura de los asentamientos humanos en los distintos países49. Recientemente se han promovido nuevos métodos para superar estos problemas, especialmente en los países de renta alta50. Éstos se basan en imágenes de satélite y en la ocupación del suelo, pero también en definiciones funcionales, por ejemplo, teniendo en cuenta la totalidad de las zonas de desplazamiento que rodean las ciudades.
Para identificar los asentamientos urbanos y rurales a nivel de celda de cuadrícula, adoptamos el tipo de cobertura del suelo MODIS MCD12Q1 V6 de 201726 de la clasificación anual de la Universidad de Maryland (con una resolución de 500 m) en combinación con la población LandScan de 2017 (resolución de 1 km). Ambos conjuntos de datos se actualizan anualmente. Para las zonas urbanas, se utiliza el tipo de ocupación del suelo 13 (tierras urbanas y urbanizadas) como condición necesaria, en combinación con una densidad de población superior a umbrales específicos de hab - km-2.

En la Tabla suplementaria 1 se enumeran los grupos de países y los umbrales correspondientes que se han definido y aplicado para minimizar la discrepancia con la división entre población urbana y rural comunicada por el Banco Mundial para 2017 ([https://data.worldbank.org/](https://data.worldbank.org/)). Las bandas de umbrales se solapan parcialmente con las regiones geográficas, como África meridional, donde se considera que un umbral de más de 650 hab - km-2 predice eficazmente las zonas urbanas. No obstante, para algunos países su umbral no coincide con su región y se insertaron en agrupaciones de densidad que permitieron una mejor estimación de su tasa de urbanización notificada. Para los asentamientos rurales, se consideró la superficie de tierra con una densidad de población inferior a la del umbral de cada conglomerado. Se descartaron los terrenos no poblados.


El planteamiento da como resultado una estimación muy coherente (R2 = 0,84 y error estándar residual de 0,067 en una regresión lineal simple) con respecto a las cifras de división de la población del Banco Mundial y las Naciones Unidas basadas en las estadísticas nacionales oficiales de los países. La Fig. 1 suplementaria muestra la predicción obtenida con el enfoque.

[https://sedac.ciesin.columbia.edu/mapping/popgrid/#](https://sedac.ciesin.columbia.edu/mapping/popgrid/#)

**Estimación del acceso a la electricidad**. Una gran cantidad de literatura ha demostrado que los lugares donde los sensores satelitales no pueden detectar la luz visible son probablemente áreas donde las personas viven sin acceso a la electricidad28-30,51. Calculamos el valor mediano de la radiancia dentro de cada píxel de los compuestos mensuales NPP-VIIRS tanto para 2014 como para 2018 dentro de la plataforma Google Earth Engine; se fijó un límite inferior de ruido en 0.25 $\mu W \cdot cm^{-2} \cdot sr^{-1}$ para 2014 y en 0.35 $\mu W \cdot cm^{-2} \cdot sr^{-1}$ para 2018 para eliminar el ruido de calibración y las luces efímeras, tal como se analiza en la literatura pertinente52-55. La discrepancia en los límites de ruido se justifica por el aumento del ruido de los datos obtenidos a partir de 2017. Según la opinión de los expertos, esto se debe a los ajustes de calibración en la corrección lunar y al lanzamiento de un nuevo satélite equipado con VIIRS (JPSS J1) en 2017 (como se analiza en56). La dispersión en el conjunto de límites inferiores de ruido antes y después de 2017 se determinó a partir del examen de píxeles de radiancia cero por definición -como dentro de grandes masas de agua- que, no obstante, presentan una radiancia sistemáticamente positiva para los datos desde 2017, y una radiancia sistemáticamente cero para los datos anteriores. Consulte la Información complementaria para ver histogramas que comparan la distribución del ruido de fondo antes y después de 2017 para la misma zona no poblada. 

Se han elaborado recuentos de población dentro de cada una de las provincias de nivel 1 de GADM tanto para las personas que viven en zonas iluminadas (por encima de 0.25/0.35 $\mu W \cdot cm^{-2} \cdot sr^{-1}$) como en zonas oscuras (≤0.25/0.35 $\mu W \cdot cm^{-2} \cdot sr^{-1}$). La clasificación cuadriculada de 1 km se utilizó para agregar los resultados cuadriculados en características espaciales poligonales que representaban los límites administrativos provinciales y nacionales. La agregación de los datos reticulares se consigue asumiendo que las celdas reticulares pertenecen al polígono que contiene su centroide. Para proporcionar un ejemplo de los datos de salida, la Fig. 2 muestra una instantánea de la densidad estimada de personas sin acceso a la electricidad en Uganda en 2018.



**clasificación de los niveles de consumo**. Estudios anteriores han demostrado que el consumo residencial de electricidad puede predecirse con precisión a partir de datos de NTL (nighttime light) obtenidos por satélite, tanto a nivel nacional57 como provincial58. Aquí, consideramos una medida de la radiancia para aquellos que se estima que viven en zonas con acceso a la electricidad. Basándonos en la distribución de los valores de los cuartiles de radiancia luminosa distinta de cero en los países del ASS (Fig. suplementaria 2), se definieron cuatro niveles de consumo eléctrico residencial, con umbrales fijados en el valor medio de cada distribución de cuartiles. Con el fin de tener en cuenta la fuerte discontinuidad urbano-rural en la iluminación, esto se hizo por separado para los asentamientos urbanos y rurales. La clasificación de los asentamientos -y, por tanto, indirectamente también de los niveles- se basa en los datos de densidad de población y tiene en cuenta la heterogeneidad de las densidades en los distintos países, como se ha descrito anteriormente. En la Tabla 2 se indican los umbrales de los niveles correspondientes.
Los cuatro niveles se validan con datos de encuestas coherentes con el marco multinivel del Banco Mundial59 , como se explica en la sección Validación técnica. Los datos por niveles se pueden asignar a un conjunto de datos de población cuadriculados para obtener la proporción de población con acceso a la electricidad en cada nivel de consumo, tanto en zonas urbanas como rurales.

